services:
    cleverage_ui_process.command.user_create:
        class: CleverAge\ProcessUiBundle\Command\UserCreateCommand
        public: false
        tags:
            - { name: console.command }
        arguments:
            - '@validator'
            - '@security.user_password_hasher'
            - '@doctrine.orm.entity_manager'
