services:
    cleverage_ui_process.command.user_create:
        class: CleverAge\UiProcessBundle\Command\UserCreateCommand
        public: false
        tags:
            - { name: console.command }
        arguments:
            - '%cleverage_ui_process.entity.user.class%'
            - '@validator'
            - '@security.user_password_hasher'
            - '@doctrine.orm.entity_manager'
