services:
    CleverAge\UiProcessBundle\Controller\:
        resource: '../../src/Controller/'
        autowire: true
        autoconfigure: true
        bind:
            $processConfigurationsManager: '@cleverage_ui_process.manager.process_configuration'
            $localeSwitcher: '@translation.locale_switcher'
            $requestStack: '@request_stack'
            $messageBus: '@messenger.default_bus'
            $uploadDirectory: '%upload_directory%'
            $context: '@EasyCorp\Bundle\EasyAdminBundle\Factory\AdminContextFactory'
            $logDirectory: '%kernel.logs_dir%'
            $processExecutionRepository: '@cleverage_ui_process.repository.process_execution'
            CleverAge\ProcessBundle\Registry\ProcessConfigurationRegistry $processConfigurationRegistry: '@cleverage_process.registry.process_configuration'
            Symfony\Component\Security\Core\Role\RoleHierarchy $roleHierarchy: '@security.role_hierarchy'
            Symfony\Contracts\Translation\TranslatorInterface $translator: '@translator'
        tags:
            - { name: 'controller.service_arguments' }
