services:
    CleverAge\ProcessUiBundle\Controller\:
        resource: '../../src/Controller/'
        autowire: true
        autoconfigure: true
        bind:
            $processConfigurationsManager: '@cleverage_ui_process.manager.process_configuration'
            $localeSwitcher: '@translation.locale_switcher'
            $request: '@request_stack'
            $messageBus: '@messenger.default_bus'
            $uploadDirectory: '%upload_directory%'
            $context: '@EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext'
            $logDirectory: '%kernel.logs_dir%'
        tags:
            - { name: 'controller.service_arguments' }
