services:
    CleverAge\ProcessUiBundle\Controller\:
        resource: '../../src/Controller/'
        autowire: true
        autoconfigure: true
        bind:
            $processLogDir: '%process_logs_dir%'
            $indexLogs: '%clever_age_process_ui.index_logs.enabled%'
        tags:
            - { name: 'controller.service_arguments' }
