services:
    cleverage_ui_process.http_value_resolver.http_process_execute:
        class: CleverAge\UiProcessBundle\Http\ValueResolver\HttpProcessExecuteValueResolver
        public: false
        arguments:
            - '%upload_directory%'

    cleverage_ui_process.http_value_resolver.process_configuration:
        class: CleverAge\UiProcessBundle\Http\ValueResolver\ProcessConfigurationValueResolver
        public: false
        arguments:
            - '@cleverage_process.registry.process_configuration'
