services:
    cleverage_ui_process.manager.configuration:
        class: CleverAge\ProcessUiBundle\Manager\ProcessUiConfigurationManager
        public: false
        arguments:
            - '@cleverage_process.registry.process_configuration'

    CleverAge\ProcessUiBundle\Manager\ProcessUiConfigurationManager:
        alias: 'cleverage_ui_process.manager.configuration'
