services:
    cleverage_ui_process.monolog_handler.doctrine_process:
        class: CleverAge\ProcessUiBundle\Monolog\Handler\DoctrineProcessHandler
        public: false
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]
            - [ setProcessExecutionManager, [ '@cleverage_ui_process.manager.process_execution' ] ]

    cleverage_ui_process.monolog_handler.process:
        class: CleverAge\ProcessUiBundle\Monolog\Handler\ProcessHandler
        public: false
        arguments:
            - '%kernel.logs_dir%'
            - '@cleverage_ui_process.manager.process_execution'

