services:
    cleverage_ui_process.repository.process_execution:
        class: CleverAge\ProcessUiBundle\Repository\ProcessExecutionRepository
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'

    cleverage_ui_process.repository.process_schedule:
        class: CleverAge\ProcessUiBundle\Repository\ProcessScheduleRepository
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'

