services:
    cleverage_ui_process.scheduler.cron:
        class: CleverAge\ProcessUiBundle\Scheduler\CronScheduler
        public: false
        arguments:
            - '@cleverage_ui_process.repository.process_schedule'
            - '@validator'
            - '@logger'
