services:
    cleverage_ui_process.security.http_process_execution_authenticator:
        class: CleverAge\UiProcessBundle\Security\HttpProcessExecutionAuthenticator
        public: false
        arguments:
            - '@cleverage_ui_process.repository.user'

