services:
    cleverage_ui_process.validator.cron_expression_validator:
        class: CleverAge\UiProcessBundle\Validator\CronExpressionValidator
        public: false
        tags:
            - { name: 'validator.constraint_validator' }

    cleverage_ui_process.validator.every_expression_validator:
        class: CleverAge\UiProcessBundle\Validator\EveryExpressionValidator
        public: false
        tags:
            - { name: 'validator.constraint_validator' }

    cleverage_ui_process.validator.is_valid_process_code:
        class: CleverAge\UiProcessBundle\Validator\IsValidProcessCodeValidator
        public: false
        tags:
            - { name: 'validator.constraint_validator' }
        arguments:
            - '@cleverage_process.registry.process_configuration'

